# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5516ab4e26a31ff81734e10d87e13cc1a238a03b1a3eee08fbae16e6a473241878c859baef1d2ec115850747e73d5f4248582aafd5639900a6c3790a1b99723

test:
  secret_key_base: 07e0a9838c3f36fcb3a8e204445b528d66f209419f3dafdff4388a50d3bfbabf5d83de5f01f80747d66bff92a02dafb909579721cbb3af292d6baad06e8e8a35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
